### ISSUE TITLE
Cannot add episode from search when anime not in list

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/zerotwo#176] opened 2020-02-18 18:45 UTC
**To Reproduce**
Search an anime not in your list and try pressing the + button

**Expected behavior**
It should add it in your list and add one episode

**Desktop:**
 - OS: Winzozz 10
 - Browser: Chrome

**Comment by NicoAiko** [comment] 2020-02-20 15:30
More or less a duplicate of #157 
Going to be fixed in upcoming release.

**Closed by NicoAiko** 2020-02-20 15:30 UTC
Labels: Bug
